### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by iamsdas** [Le1s/proprietary_vendor_leeco#1]
I have used your sources to build lineage OS 14.1.
In this build the camera and the flashlight is not working. Is this a common bug? Any idea how to get it working ? Is there any patch to make camera work because I did not find any.

**Comment by DarkAbhi** [comment]
@SuryashankarDas

**Comment by SscSPs** [comment]
@SuryashankarDas Well, I know we've talked about this already. Most likely, we need to work on camera related configs in device tree, and not in vendor.

**Comment by DarkAbhi** [comment]
@SuryashankarDas Temporary Solution for Lineage and RR ROMS
-Replace camera files from latest RR to your build-

**Comment by iamsdas** [comment]
Enable issues in your device tree. This was the only way I had to contact you right now. How did wisniaPl enable the camera and flash? He did not upload the camera related stuff?

**Comment by iamsdas** [comment]
@DarkAbhi ,which files to replace?

**Comment by DarkAbhi** [comment]
@SuryashankarDas No he is too private.

**Comment by iamsdas** [comment]
So which files to copy?

**Comment by iamsdas** [comment]
I was comparing files with RR. It seems that some .so files are missing in the vendor tree. These are the files I guess he did not upload.

**Comment by SscSPs** [comment]
@SuryashankarDas it wont work to directly put those files in the tree,

**Comment by iamsdas** [comment]
It will, I mean those files will get copied to the right place I made sure. Is there anything more to do?

**Comment by SscSPs** [comment]
@SuryashankarDas try it and tell if it works

**Comment by iamsdas** [comment]
I compared the RR and my los .zip files

**Comment by SscSPs** [comment]
@SuryashankarDas someone tried and it didn't

**Comment by iamsdas** [comment]
Do you mean the camera.default.so?

**Comment by SscSPs** [comment]
I am not entirely sure how he tried, so go ahead and give it a try, try to put the files in Vendor tree

**Comment by iamsdas** [comment]
with only those files it did not work, but i found many more .so files in RR. I am trying with those now, there were MANY different files. But i do not know if all are supposed to be in the vendor tree or are they generated during build.

**Comment by SscSPs** [comment]
Ok, here are few steps you can take:
1. Flash your ROM, 
2. Pull files from from Wisniapl's ROM and put it in your device
3. if it works, cool, collect all those files and put them in respective places in vendor tree.
 OR
 if it doesn't work, pull more files, and redo from step 2.
4. Try to build ROM again with new vendor tree.
5. See if you get some error during build process and try to fix it (if you want, you can ask here too).
6. If it builds properly, go ahead and flash it and try.
 OR
if it doesn't, try removing some files from vendor tree and do it again.
IF in the end, it works, GREAT! You found a solution for our device's CAMERA bug.
if not, good try.

PS: Don't forget to install the patches if you uninstalled it

**Comment by iamsdas** [comment]
In the install.sh in patches folder there are many patches that do not exist like in the directories -bionic frameworks/av frameworks/base frameworks/native hardware/libhardware etc. So I removed them. That was the right thing to do right? And I noticed that wisniapl did not update the vendor tree , he has changed many files but has not uploaded them. After a lot of trials and errors of getting the camera to work , still no luck. Is there anything supposed to be changed in the device tree too?

**Comment by SscSPs** [comment]
@SuryashankarDas Well, about the patches, yes it was right thigh to do. 
And about the files, yea, he did not upload his changes, We need to work on it to make the camera work. Se files are forcibly generated during the build process and We can't use prebuilt ones during build process. 
I've been a bit busy lately to continue the work, but I'll resume working on it soon. Hope we might have a good working camera soon

**Comment by DroidThug** [comment]
@SuryashankarDas For failed patches, check the diff patchsets and apply them manually

**Comment by iamsdas** [comment]
@DroidThug , in my nougat aokp build while applying patches it shows some stuff not found in  something.java . I know that it is meant for the intent for opening browser when clicking author name. Is there any chance that it will cause boot isuue if the .XML file is edited but not the .java file?

**Comment by iamsdas** [comment]
@SscSPs , during the build process there are many warnings like make: something.so  ignored. So I am guessing these were supposed to be generated automatically during the build. But many of those files are there in vendor tree. Now out of the many new .so files I found in RR.zip , is there any way to differentiate which ones are supposed to be in the vendor tree and which ones are auto generated and may create conflicts with my lineage os build?

**Comment by SscSPs** [comment]
@SuryashankarDas Put them in vendor and see what's ignored

**Comment by iamsdas** [comment]
@SscSPs , by ignored I mean that they were supposed to be generated but that command is ignored because I already have the file in the vendor tree. So if the file was not supposed to be there it may create conflicts and the ROM may not boot.

**Comment by SscSPs** [comment]
@SuryashankarDas No, it wont.
if it is to be generated automatically, it will just not pick it up from the vendor directory.
When you do "make bacon", it'll list all the files that are ignored. check that and you can just remove those files from vendor.
